name: share_app
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  smooth_page_indicator: ^1.1.0
  cupertino_icons: ^1.0.6