name: share_app
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^10.1.0 # Location detect karne ke liye
  geocoding: ^2.1.1 # Address nikalne ke liye
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0 # Onboarding dots ke liye