name: share_app
description: A gaming top-up store
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  smooth_page_indicator: ^1.1.0
  cupertino_icons: ^1.0.6
  carousel_slider: ^4.0.0   # fixed version to avoid conflict
  qr_flutter: ^4.1.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true