name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Clean & Re-create Android
        run: |
          rm -rf android
          flutter create . --platforms=android

      - name: Auto Inject Permissions
        run: |
          MANIFEST="android/app/src/main/AndroidManifest.xml"
          # Adding essential permissions for location and internet
          sed -i '/<application/i \    <uses-permission android:name="android.permission.INTERNET" />' $MANIFEST
          sed -i '/<application/i \    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />' $MANIFEST
          sed -i '/<application/i \    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />' $MANIFEST

      - run: flutter pub get
      - run: flutter build apk --release

      - name: Move APK to Workspace Root
        run: cp build/app/outputs/flutter-apk/app-release.apk ./XSale_Build_Final.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Final-XSale-APK
          path: XSale_Build_Final.apk