name: Build Flutter APK

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: # Allows you to run it manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Updated to v4 ✅
      - name: Checkout repository
        uses: actions/checkout@v4

      # Updated to v4 ✅
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Yeh automatically latest stable flutter version lega

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      # Updated to v4 ✅ (Yahi error de raha tha)
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk